
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    ports:
      - "3306:3306"
    networks:
      - digital-money-house
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-eureka:
    image: openjdk:17
    container_name: api-eureka
    build:
      context: ./api-eureka
    ports:
      - "8761:8761"
    networks:
      - digital-money-house

  api-config:
    image: openjdk:17
    container_name: api-config
    build:
      context: ./api-config
    ports:
      - "8864:8864"
    networks:
      - digital-money-house
    depends_on:
      api-eureka:
        condition: service_started

  api-gateway:
    image: openjdk:17
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - digital-money-house
    depends_on:
      - api-eureka
      - api-config
      - user-service
      - cuenta-service
      - transaccion-service
      - api-tarjetas
    environment:
      SPRING_PROFILES_ACTIVE: docker

  user-service:
    image: openjdk:17
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - "8086:8086"
    networks:
      - digital-money-house
    depends_on:
      mysql-db:
        condition: service_healthy
      api-eureka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/usuarios?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE: docker

  cuenta-service:
    image: openjdk:17
    container_name: cuenta-service
    build:
      context: ./cuenta-service
    ports:
      - "8081:8081"
    networks:
      - digital-money-house
    depends_on:
      mysql-db:
        condition: service_healthy
      api-eureka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/usuarios?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE: docker

  transaccion-service:
    image: openjdk:17
    container_name: transaccion-service
    build:
      context: ./transaccion-service
    ports:
      - "8082:8082"
    networks:
      - digital-money-house
    depends_on:
      mysql-db:
        condition: service_healthy
      api-eureka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/usuarios?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE: docker

  api-tarjetas:
    image: openjdk:17
    container_name: api-tarjetas
    build:
      context: ./api-tarjetas
    ports:
      - "8083:8083"
    networks:
      - digital-money-house
    depends_on:
      mysql-db:
        condition: service_healthy
      api-eureka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/usuarios?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE: docker

networks:
  digital-money-house:
    driver: bridge

volumes:
  mysql_data:
